{{- if  .Values.prometheus.serviceMonitor.kafka.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: pnda
  name: kafka
  namespace: {{ .Values.prometheus.serviceMonitor.kafka.namespace | default .Release.Namespace }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheus.serviceMonitor.kafka.interval }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: kafka
{{- end }}
