{{- if and .Values.strimzi .Values.strimzi.kafka -}}
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: strimzi
spec:
  kafka:
    version: 2.3.1
    replicas: {{ .Values.strimzi.kafka.replicas }}
    jmxOptions: {}
    metrics: {}
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
    config:
      {{- if lt .Values.strimzi.kafka.replicas 3.0 }}
      offsets.topic.replication.factor:  1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      {{- else }}
       offsets.topic.replication.factor:  3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      {{- end }}
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
  zookeeper:
    replicas: {{ .Values.strimzi.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

{{- end }}