{{- if .Values.prometheus.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name}}-hbase-region-metrics
  labels:
   app: hbase
   component: regionserver
spec: 
  selector: 
    app: {{ include "hbase.name" . }}
    release: {{ .Release.Name }}
    component: regionserver
  ports:
  - port: {{ .Values.prometheus.port }}
    name: metrics
    targetPort: {{ .Values.prometheus.port }}
{{- end -}}