dependencies:
# We should manually install strimzi operator. (See README.md requirements section)
- name: schema-registry
  version: ~1.1.8
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  alias: schemaregistry
  condition: schema-registry.enabled
- name: schema-registry-ui
  version: ~0.4.1
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: schemaregistry-ui
  condition: schema-registry-ui.enabled
- name: kafka-connect-ui
  version: ~0.1.0
  repository: https://gradiant.github.io/charts
  condition: kafka-connect-ui.enabled
- name: kafka-manager
  version: ~2.2.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: kafka-manager.enabled
- name: jupyterhub
  version: 0.9.0-beta.3
  repository: https://jupyterhub.github.io/helm-chart/
  condition: jupyterhub.enabled
- name: sparkoperator
  version: ~0.6.1
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  condition: sparkoperator.enabled
- name: spark-standalone
  version: ~0.1.0
  repository: https://gradiant.github.io/charts
  condition: spark-standalone.enabled
- name: hdfs
  version: ~0.1.0
  repository: https://gradiant.github.io/charts
  condition: hdfs.enabled
- name: hbase
  version: ~0.1.0
  repository: https://gradiant.github.io/charts
  condition: hbase.enabled
- name: opentsdb
  version: ~0.1.0
  repository: https://gradiant.github.io/charts
  condition: opentsdb.enabled
- name: grafana
  version: ~4.0.4
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: grafana.enabled
- name: elasticsearch
  version: ~7.4.0
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: kibana
  version: ~7.4.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: redis
  version: ~9.5.5
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: rebase.enabled
- name: jmxproxy
  version: ~0.1.0
  repository: file://../jmxproxy
