{{- if  .Values.prometheus.serviceMonitor.kafka.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: prometheus-monitoring
    {{- include "pnda.labels" . | nindent 4 }}
  namespace: {{ .Values.prometheus.serviceMonitor.kafka.namespace | default .Release.Namespace }}
spec:
  endpoints:
  - port: prometheus
    interval: {{ .Values.prometheus.serviceMonitor.kafka.interval }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:                
      strimzi.io/cluster: strimzi                           
      strimzi.io/kind: Kafka                                
      strimzi.io/name: strimzi-kafka-bootstrap 
{{- end }}
