apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pnda.console-backend-data-manager.fullname" . }}
  labels:
    {{- include "pnda.console-backend-data-manager.labels" . | nindent 4 }}
data:
  config.js: |-
    module.exports = {
      whitelist: ['http://{{ include "pnda.data-service.fullname" . }}:7000', 'http://{{ include "pnda.deployment-manager.fullname" . }}:5000'],
      deployment_manager: {
        host: "http://{{ include "pnda.deployment-manager.fullname" . }}:5000",
        API: {
          endpoints: "/environment/endpoints",
          packages_available: "/repository/packages?recency=999",
          packages: "/packages",
          applications: "/applications"
        }
      },
      dataset_manager: {
        host: "http://{{ include "pnda.data-service.fullname" . }}:7000",
        API: {
          datasets: "/api/v1/datasets"
        }
      },
      session: {
        secret: "data-manager-secret",
        max_age: 86400000,
        session_expiry_warning_duration: 30000
      }
    };
